### ISSUE TITLE
Provide a callback to notify which items were evicted

### ISSUE THREAD

**Issue by zenabo1** [cachelot/cachelot#12]
Hi! I'm using cachelot and it seems very interesting. However i'm facing one problem. There is a way to know the content that has been evicted?
Like to write in a file the key that was evicted.

**Comment by aka-rider** [comment]
Hi @zenabo1 

Thanks for the feedback.
There is internal callback in the Cachelot's memalloc that removes evicted item from the hash table but it's not part of the public API.
I think it'll be a reasonable feature to provide "on evicted" callback in the API. I will include it in the next release (1-2 weeks ETA).

**Comment by aka-rider** [comment]
Hi @zenabo1 
Eviction callback is in master.

C++ API: `Cache::on_eviction` 
C API: `cachelot_on_eviction_callback`

**Comment by zenabo1** [comment]
Hello @aka-rider 
Thank's for your time. But I do not understand where the keys are being displayed when it begins to have evictions. I am using cachelot out of my machine via tcp, and i want to inform another machine which keys were cleared/evictioned. For this I think its only need to write in a text file the keys that are being dumped/evictioned. I do not know if it's possible?

**Comment by aka-rider** [comment]
Hello @zenabo1 

> But I do not understand where the keys are being displayed when it begins to have evictions. 
There is no way to show evicted keys, any attempt to do that would drastically drop performance.
