### ISSUE TITLE
Question:  Atomic operations

### ISSUE THREAD

**Issue by rohitjoshi** [cachelot/cachelot#14]
Great work here 👍 

I am planning to create a Rust wrapper around C-API and use in my rust program.  My use-case is a pre-allocate 100GB memory for cache and use as LRU cache.  The cache will be initialized from DB or file at startup and mostly used for read-only except if DB records are changes. 

Are the insert,  read and update atomic operation or mutex lock is required?

**Comment by aka-rider** [comment]
Hi. Thank you.

> I am planning to create a Rust wrapper around C-API and use in my rust program. My use-case is a pre-allocate 100GB memory for cache and use as LRU cache.
Yep. That's the ideal case.

>Are the insert, read and update atomic operation or mutex lock is required?
Mutex is required. Cachelot was made single-threaded intentionally, as even atomics `cmpxchg` and similar are hurting performance. So locking mechanism is left to end-user (if required).

Let me know if you have any other questions.
Cheers.
