### ISSUE TITLE
Ubuntu daemon can't work

### ISSUE THREAD

**Issue by fslove** [cachelot/cachelot#15]
./cachelotd -C -d

**Comment by aka-rider** [comment]
Thanks, @fslove for raising this issue. 
Actually, daemon mode is not implemented at all. I left `-d` switch for better compatibility (I see now that it's somewhat misleading).

Currently, I don't have time to fix this.

As a workaround, I would recommend running cachelotd under _systemd_, _docker_, or similar. It's also possible to wrap it with an init-like script instead.

**Comment by fslove** [comment]
Thank your reply.
