### ISSUE TITLE
test_c_api problem

### ISSUE THREAD

**Issue by fslove** [cachelot/cachelot#16]
![image](https://user-images.githubusercontent.com/10248063/34855195-57e463b0-f779-11e7-9a46-67a8d4216420.png)

**Comment by aka-rider** [comment]
Hi @fslove
Thanks for reporting this. It's not a bug -- cachelot failed to pre-allocate 4Gb of RAM (std::bad_alloc means out of memory).
I should make test allocations less aggressive.

**Comment by fslove** [comment]
@aka-rider thank your reply . :+1:
