### ISSUE TITLE
Build for Freebsd

### ISSUE THREAD

**Issue by senioi** [cachelot/cachelot#17]
```
-- Build files have been written to: /root/cachelot
[ 15%] Built target cachelot
[ 18%] Building CXX object src/server/CMakeFiles/cachelotd.dir/memcached/proto_ascii.cpp.o
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:15:
/root/cachelot/src/server/socket_stream.h:148:23: warning: unused variable 'receive_result' [-Wunused-variable]
                slice receive_result;
                      ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:14:
/root/cachelot/src/cachelot/bits.h:48:24: error: expected unqualified-id
        constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
                       ^
/usr/include/sys/param.h:287:5: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
           ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:14:
/root/cachelot/src/cachelot/bits.h:48:24: error: expected ')'
/usr/include/sys/param.h:287:5: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
           ^
/root/cachelot/src/cachelot/bits.h:48:24: note: to match this '('
/usr/include/sys/param.h:287:4: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
          ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:14:
/root/cachelot/src/cachelot/bits.h:48:66: error: expected ')'
        constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
                                                                 ^
/root/cachelot/src/cachelot/bits.h:48:24: note: to match this '('
        constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
                       ^
/usr/include/sys/param.h:287:32: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
                                      ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:14:
/root/cachelot/src/cachelot/bits.h:48:24: error: expected expression
        constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
                       ^
/usr/include/sys/param.h:287:35: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
                                         ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:14:
/root/cachelot/src/cachelot/bits.h:48:24: error: expected ')'
/usr/include/sys/param.h:287:42: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
                                                ^
/root/cachelot/src/cachelot/bits.h:48:24: note: to match this '('
/usr/include/sys/param.h:287:2: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
        ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:14:
/root/cachelot/src/cachelot/bits.h:112:16: error: no member named 'most_significant' in namespace 'cachelot::bit'; did you mean 'significand'?
        return bit::most_significant(value);
               ^~~~~~~~~~~~~~~~~~~~~
               significand
/usr/include/math.h:337:8: note: 'significand' declared here
double  significand(double);
        ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:150:
/root/cachelot/src/cachelot/memalloc-inl.h:462:25: error: expected unqualified-id
            return bit::isset(first_level_bit_index, pos.pow_index) && bit::isset(second_level_bit_index[pos.pow_index], pos.sub_index);
                        ^
/usr/include/sys/param.h:287:2: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
        ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:150:
/root/cachelot/src/cachelot/memalloc-inl.h:462:25: warning: cast to 'const unsigned char *' from smaller integer type 'cachelot::uint32' (aka 'unsigned int') [-Wint-to-pointer-cast]
/usr/include/sys/param.h:287:4: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
          ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:150:
/root/cachelot/src/cachelot/memalloc-inl.h:462:77: error: expected unqualified-id
            return bit::isset(first_level_bit_index, pos.pow_index) && bit::isset(second_level_bit_index[pos.pow_index], pos.sub_index);
                                                                            ^
/usr/include/sys/param.h:287:2: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
        ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:150:
/root/cachelot/src/cachelot/memalloc-inl.h:462:77: warning: cast to 'const unsigned char *' from smaller integer type 'std::__1::__vector_base<unsigned int, std::__1::allocator<unsigned int> >::value_type' (aka 'unsigned int')
      [-Wint-to-pointer-cast]
/usr/include/sys/param.h:287:4: note: expanded from macro 'isset'
        (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
          ^
In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
In file included from /root/cachelot/src/server/memcached/memcached.h:21:
In file included from /root/cachelot/src/cachelot/cache.h:12:
In file included from /root/cachelot/src/cachelot/memalloc.h:150:
/root/cachelot/src/cachelot/memalloc-inl.h:468:58: error: no member named 'unset' in namespace 'cachelot::bit'
            second_level_bit_index[pos.pow_index] = bit::unset(second_level_bit_index[pos.pow_index], pos.sub_index);
                                                    ~~~~~^
/root/cachelot/src/cachelot/memalloc-inl.h:471:46: error: no member named 'unset' in namespace 'cachelot::bit'
                first_level_bit_index = bit::unset(first_level_bit_index, pos.pow_index);
                                        ~~~~~^
/root/cachelot/src/cachelot/memalloc-inl.h:477:58: error: no member named 'set' in namespace 'cachelot::bit'
            second_level_bit_index[pos.pow_index] = bit::set(second_level_bit_index[pos.pow_index], pos.sub_index);
                                                    ~~~~~^

[freebsd][                                                                                                    (0*$ csh)                                                                                                    ][08/22/18  7:34 PM]
/root/cachelot/src/cachelot/memalloc-inl.h:478:42: error: no member named 'set' in namespace 'cachelot::bit'
            first_level_bit_index = bit::set(first_level_bit_index, pos.pow_index);
                                    ~~~~~^
/root/cachelot/src/cachelot/memalloc-inl.h:492:89: error: no member named 'least_significant' in namespace 'cachelot::bit'
                    return tuple<bool, position>(true, position(current.pow_index, bit::least_significant(next_sub_index_mask)));
                                                                                   ~~~~~^
/root/cachelot/src/cachelot/memalloc-inl.h:499:51: error: no member named 'least_significant' in namespace 'cachelot::bit'
                    const uint32 next_pow2 = bit::least_significant(next_pow2_mask);
                                             ~~~~~^
/root/cachelot/src/cachelot/memalloc-inl.h:501:81: error: no member named 'least_significant' in namespace 'cachelot::bit'
                    return tuple<bool, position>(true, position(next_pow2, bit::least_significant(second_level_bit_index[next_pow2])));
                                                                           ~~~~~^
3 warnings and 15 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /root/cachelot
*** Error code 1
```

**Comment by senioi** [comment]
gcc:

- root@freebsd:~/cachelot # cmake -DCMAKE_C_COMPILER=/usr/local/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/bin/g++
- -- The C compiler identification is GNU 6.4.0
- -- The CXX compiler identification is GNU 6.4.0
- -- Check for working C compiler: /usr/local/bin/gcc
- -- Check for working C compiler: /usr/local/bin/gcc -- works
- -- Detecting C compiler ABI info
- -- Detecting C compiler ABI info - done
- -- Detecting C compile features
- -- Detecting C compile features - done
- -- Check for working CXX compiler: /usr/local/bin/g++
- -- Check for working CXX compiler: /usr/local/bin/g++ -- works
- -- Detecting CXX compiler ABI info
- -- Detecting CXX compiler ABI info - done
- -- Detecting CXX compile features
- -- Detecting CXX compile features - done
- -- Platform: FreeBSD x64
- -- Compiler ID: GNU
- -- gcc version 6.4.0
- -- Looking for aligned_alloc
- -- Looking for aligned_alloc - found
- -- Looking for posix_memalign
- -- Looking for posix_memalign - found
- -- Boost version: 1.67.0
- -- Found the following Boost libraries:
- --   unit_test_framework
- --   system
- --   program_options
- -- Cachelot setup ...
- -- Configuring done
- -- Generating done
- -- Build files have been written to: /root/cachelot

make:

1. root@freebsd:~/cachelot # make
2. [ 15%] Built target cachelot
3. [ 18%] Building CXX object src/server/CMakeFiles/cachelotd.dir/memcached/proto_ascii.cpp.o
4. In file included from /usr/local/include/boost/predef/os/bsd/free.h:37:0,
5.                  from /usr/local/include/boost/predef/os/bsd.h:96,
6.                  from /usr/local/include/boost/predef/os/bsd/dragonfly.h:11,
7.                  from /usr/local/include/boost/predef/os/bsd.h:95,
8.                  from /usr/local/include/boost/predef/os/bsd/bsdi.h:11,
9.                  from /usr/local/include/boost/predef/os/bsd.h:52,
10.                  from /usr/local/include/boost/predef/os.h:18,
11.                  from /usr/local/include/boost/predef.h:17,
12.                  from /usr/local/include/boost/smart_ptr/detail/yield_k.hpp:28,
13.                  from /usr/local/include/boost/smart_ptr/detail/spinlock_std_atomic.hpp:18,
14.                  from /usr/local/include/boost/smart_ptr/detail/spinlock.hpp:47,
15.                  from /usr/local/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
16.                  from /usr/local/include/boost/smart_ptr/shared_ptr.hpp:36,
17.                  from /usr/local/include/boost/shared_ptr.hpp:17,
18.                  from /usr/local/include/boost/date_time/time_clock.hpp:17,
19.                  from /usr/local/include/boost/date_time/posix_time/posix_time_types.hpp:10,
20.                  from /usr/local/include/boost/asio/time_traits.hpp:23,
21.                  from /usr/local/include/boost/asio/basic_deadline_timer.hpp:28,
22.                  from /usr/local/include/boost/asio.hpp:24,
23.                  from /root/cachelot/src/server/network.h:31,
24.                  from /root/cachelot/src/server/socket_stream.h:11,
25.                  from /root/cachelot/src/server/memcached/memcached.h:15,
26.                  from /root/cachelot/src/server/memcached/proto_ascii.h:10,
27.                  from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
28. /root/cachelot/src/cachelot/bits.h:48:24: error: expected unqualified-id before 'const'
29.          constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
30.                         ^
31. /root/cachelot/src/cachelot/bits.h:48:24: error: expected ')' before 'const'
32. /root/cachelot/src/cachelot/bits.h:48:24: error: expected ')' before 'const'
33. /root/cachelot/src/cachelot/bits.h:48:24: error: expected ')' before 'const'
34. /root/cachelot/src/cachelot/memalloc-inl.h: In member function 'bool cachelot::memalloc::free_blocks_by_size::bit_index_probe(cachelot::memalloc::free_blocks_by_size::position) const':
35. /root/cachelot/src/cachelot/memalloc-inl.h:462:25: error: expected unqualified-id before '(' token
36.              return bit::isset(first_level_bit_index, pos.pow_index) && bit::isset(second_level_bit_index[pos.pow_index], pos.sub_index);
37.                          ^
38. /root/cachelot/src/cachelot/memalloc-inl.h:462:77: error: expected unqualified-id before '(' token
39.              return bit::isset(first_level_bit_index, pos.pow_index) && bit::isset(second_level_bit_index[pos.pow_index], pos.sub_index);
40.                                                                              ^
41. *** Error code 1
42. 
43. Stop.
44. make[2]: stopped in /root/cachelot
45. *** Error code 1
46. 
47. Stop.
48. make[1]: stopped in /root/cachelot
49. *** Error code 1
50. 
51. Stop.
52. make: stopped in /root/cachelot

**Comment by senioi** [comment]
clang:

- root@freebsd:~/cachelot # cmake -DCMAKE_C_COMPILER=/usr/bin/cc -DCMAKE_CXX_COMPILER=/usr/bin/c++
- -- The C compiler identification is Clang 6.0.0
- -- The CXX compiler identification is Clang 6.0.0
- -- Check for working C compiler: /usr/bin/cc
- -- Check for working C compiler: /usr/bin/cc -- works
- -- Detecting C compiler ABI info
- -- Detecting C compiler ABI info - done
- -- Detecting C compile features
- -- Detecting C compile features - done
- -- Check for working CXX compiler: /usr/bin/c++
- -- Check for working CXX compiler: /usr/bin/c++ -- works
- -- Detecting CXX compiler ABI info
- -- Detecting CXX compiler ABI info - done
- -- Detecting CXX compile features
- -- Detecting CXX compile features - done
- -- Platform: FreeBSD x64
- -- Compiler ID: Clang
- -- Clang version 6.0.0
- -- Looking for aligned_alloc
- -- Looking for aligned_alloc - found
- -- Looking for posix_memalign
- -- Looking for posix_memalign - found
- -- Boost version: 1.67.0
- -- Found the following Boost libraries:
- --   unit_test_framework
- --   system
- --   program_options
- -- Cachelot setup ...
- -- Configuring done
- -- Generating done
- -- Build files have been written to: /root/cachelot


make:

> root@freebsd:~/cachelot # make
> Scanning dependencies of target cachelot
> [  3%] Building CXX object src/cachelot/CMakeFiles/cachelot.dir/common.cpp.o
> [  6%] Building CXX object src/cachelot/CMakeFiles/cachelot.dir/item.cpp.o
> [  9%] Building CXX object src/cachelot/CMakeFiles/cachelot.dir/stats.cpp.o
> [ 12%] Building CXX object src/cachelot/CMakeFiles/cachelot.dir/c_api.cpp.o
> [ 15%] Linking CXX static library ../../lib/RelWithDebugInfo/libcachelot.a
> [ 15%] Built target cachelot
> Scanning dependencies of target cachelotd
> [ 18%] Building CXX object src/server/CMakeFiles/cachelotd.dir/settings.cpp.o
> [ 21%] Building CXX object src/server/CMakeFiles/cachelotd.dir/memcached/proto_ascii.cpp.o
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:15:
> /root/cachelot/src/server/socket_stream.h:148:23: warning: unused variable 'receive_result' [-Wunused-variable]
>                 slice receive_result;
>                       ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:14:
> /root/cachelot/src/cachelot/bits.h:48:24: error: expected unqualified-id
>         constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
>                        ^
> /usr/include/sys/param.h:287:5: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>            ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:14:
> /root/cachelot/src/cachelot/bits.h:48:24: error: expected ')'
> /usr/include/sys/param.h:287:5: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>            ^
> /root/cachelot/src/cachelot/bits.h:48:24: note: to match this '('
> /usr/include/sys/param.h:287:4: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>           ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:14:
> /root/cachelot/src/cachelot/bits.h:48:66: error: expected ')'
>         constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
>                                                                  ^
> /root/cachelot/src/cachelot/bits.h:48:24: note: to match this '('
>         constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
>                        ^
> /usr/include/sys/param.h:287:32: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>                                       ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:14:
> /root/cachelot/src/cachelot/bits.h:48:24: error: expected expression
>         constexpr bool isset(const IntType value, const unsigned bitno) noexcept {
>                        ^
> /usr/include/sys/param.h:287:35: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>                                          ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:14:
> /root/cachelot/src/cachelot/bits.h:48:24: error: expected ')'
> /usr/include/sys/param.h:287:42: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>                                                 ^
> /root/cachelot/src/cachelot/bits.h:48:24: note: to match this '('
> /usr/include/sys/param.h:287:2: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>         ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:14:
> /root/cachelot/src/cachelot/bits.h:112:16: error: no member named 'most_significant' in namespace 'cachelot::bit'; did you mean 'significand'?
>         return bit::most_significant(value);
>                ^~~~~~~~~~~~~~~~~~~~~
>                significand
> /usr/include/math.h:337:8: note: 'significand' declared here
> double  significand(double);
>         ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:150:
> /root/cachelot/src/cachelot/memalloc-inl.h:462:25: error: expected unqualified-id
>             return bit::isset(first_level_bit_index, pos.pow_index) && bit::isset(second_level_bit_index[pos.pow_index], pos.sub_index);
>                         ^
> /usr/include/sys/param.h:287:2: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>         ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:150:
> /root/cachelot/src/cachelot/memalloc-inl.h:462:25: warning: cast to 'const unsigned char *' from smaller integer type 'cachelot::uint32' (aka 'unsigned int') [-Wint-to-pointer-cast]
> /usr/include/sys/param.h:287:4: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>           ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:150:
> /root/cachelot/src/cachelot/memalloc-inl.h:462:77: error: expected unqualified-id
>             return bit::isset(first_level_bit_index, pos.pow_index) && bit::isset(second_level_bit_index[pos.pow_index], pos.sub_index);
>                                                                             ^
> /usr/include/sys/param.h:287:2: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>         ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:150:
> /root/cachelot/src/cachelot/memalloc-inl.h:462:77: warning: cast to 'const unsigned char *' from smaller integer type 'std::__1::__vector_base<unsigned int, std::__1::allocator<unsigned int> >::value_type' (aka 'unsigned int')
>       [-Wint-to-pointer-cast]
> /usr/include/sys/param.h:287:4: note: expanded from macro 'isset'
>         (((const unsigned char *)(a))[(i)/NBBY] & (1<<((i)%NBBY)))
>           ^
> In file included from /root/cachelot/src/server/memcached/proto_ascii.cpp:2:
> In file included from /root/cachelot/src/server/memcached/proto_ascii.h:10:
> In file included from /root/cachelot/src/server/memcached/memcached.h:21:
> In file included from /root/cachelot/src/cachelot/cache.h:12:
> In file included from /root/cachelot/src/cachelot/memalloc.h:150:
> /root/cachelot/src/cachelot/memalloc-inl.h:468:58: error: no member named 'unset' in namespace 'cachelot::bit'
>             second_level_bit_index[pos.pow_index] = bit::unset(second_level_bit_index[pos.pow_index], pos.sub_index);
>                                                     ~~~~~^
> /root/cachelot/src/cachelot/memalloc-inl.h:471:46: error: no member named 'unset' in namespace 'cachelot::bit'
>                 first_level_bit_index = bit::unset(first_level_bit_index, pos.pow_index);
>                                         ~~~~~^
> /root/cachelot/src/cachelot/memalloc-inl.h:477:58: error: no member named 'set' in namespace 'cachelot::bit'
>             second_level_bit_index[pos.pow_index] = bit::set(second_level_bit_index[pos.pow_index], pos.sub_index);
>                                                     ~~~~~^
> /root/cachelot/src/cachelot/memalloc-inl.h:478:42: error: no member named 'set' in namespace 'cachelot::bit'
>             first_level_bit_index = bit::set(first_level_bit_index, pos.pow_index);
>                                     ~~~~~^
> /root/cachelot/src/cachelot/memalloc-inl.h:492:89: error: no member named 'least_significant' in namespace 'cachelot::bit'
>                     return tuple<bool, position>(true, position(current.pow_index, bit::least_significant(next_sub_index_mask)));
>                                                                                    ~~~~~^
> /root/cachelot/src/cachelot/memalloc-inl.h:499:51: error: no member named 'least_significant' in namespace 'cachelot::bit'
>                     const uint32 next_pow2 = bit::least_significant(next_pow2_mask);
>                                              ~~~~~^
> /root/cachelot/src/cachelot/memalloc-inl.h:501:81: error: no member named 'least_significant' in namespace 'cachelot::bit'
>                     return tuple<bool, position>(true, position(next_pow2, bit::least_significant(second_level_bit_index[next_pow2])));
>                                                                            ~~~~~^
> 3 warnings and 15 errors generated.
> *** Error code 1
> 
> Stop.
> make[2]: stopped in /root/cachelot
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /root/cachelot
> *** Error code 1
> 
> Stop.
> make: stopped in /root/cachelot

**Comment by aka-rider** [comment]
Hello @senioi 
Thank you very much for this issue. I will try to fix this ASAP (although, I can not jump into it right away).
It turned out, Docker image is also broken.

**Comment by senioi** [comment]
@aka-rider  Thanks

**Comment by senioi** [comment]
I hope to see it soon support FreeBSD

**Comment by aka-rider** [comment]
@senioi Should be fixed in master
