### ISSUE TITLE
Unit test failure in test_int_to_str

### ISSUE THREAD

**Issue by bftjoe** [cachelot/cachelot#29]
Running 24 test cases...
/home/joe/cachelot/src/unit_test/test_string_conv.cpp(31): error: in "test_string_conv/test_int_to_str": check my_value == their_value has failed [-9223372036854775807 != -9223372036854775808]

I'm on Ubuntu running on WSL2. 

-- Compiler: GNU v9.3.0

**Comment by aka-rider** [comment]
Hi @bftjoe 
Thank you for this bug report, I will take a look in the nearest time.

**Comment by bftjoe** [comment]
Compiling in release mode, probably due to overflow being undefined in C++

**Comment by aka-rider** [comment]
Thanks for your patience, fixed in https://github.com/cachelot/cachelot/pull/30

**Comment by aka-rider** [comment]
Please let me know if you have any questions.
