### ISSUE TITLE
why not remove the boost dependency

### ISSUE THREAD

**Issue by libratiger** [cachelot/cachelot#36]
the boost is heavy dependency, so remove it with std library make this repo more usable.

**Comment by aka-rider** [comment]
boost::asio is a dependency for the cachelot server.

As for the embedded library itself, it uses error_code, which is now a part of stdlib and could be removed, and the library uses boost::intrusive_list, which I'm not aware of the alternatives.

If boost is a concern, the cachelot could be build as a shared or dynamic library and linked. Also, cachelot provides C API wrapper, so it can be linked even with pure C code.
