### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by adamjaso** [cachelot/cachelot#4]
I've been looking around, but I haven't found any docs for cachelot. Am I right in guessing that it supports the same interface as Memcache (such that any existing memcache client will work)? The readme hinted at it, but I didn't find any direct confirmation that it supports the Memcache interface. Is cachelot a memcache replacement, or an enhancement? Are there other features in Cachelot that are not available in memcache?

**Comment by aka-rider** [comment]
Hello,

> Am I right in guessing that it supports the same interface as Memcache (such that any existing memcache client will work)?

Cachelot support almost 100% of text memcached protocol (cachelot lacks stat command argument support), so speaking of text protocol - yes. TCP/UDP/Unix domain socket available. Unfortunately, binary protocol has not implemented yet.

> Is cachelot a memcache replacement, or an enhancement?

Replacement. 
Cachelot is single-threaded to scale on many CPU cores and it has good memory footprint (up to 90-95% memory utilization, while memcached is able to utilize ~80-85%)

> Are there other features in Cachelot that are not available in memcache?

There are many planned features, but they require protocol extension or replacement.

Current plan is to implement RESTful protocol, then some features (like compression) can be implemented on top.
